### Site metadata ###

site_name: Java CTe
site_description: Projeto para consumo do webservice de CTe 
site_url: https://Samuel-Oliveira.github.io/Java_CTe/

repo_url: https://github.com/Samuel-Oliveira/Java_CTe
edit_uri: edit/master/docs/docs

### Build settings ###
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: pt-BR
  scheme: slate
  features:
    - navigation.tracking
    - navigation.expand
    - content.code.annotate

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Inicio: index.md
  - Exemplos:
      - Configurações (certificado): tutorial/configuracoes.md
      - Envio: tutorial/envio.md
      - Cancelamento: tutorial/cancelamento.md
      - Inutilização: tutorial/inutilizacao.md
      - Consulta Situação: tutorial/consulta-situacao.md
      - Carta de Correção Eletrônica: tutorial/carta-correcao.md
      - Status de Serviço Sefaz: tutorial/status-servico.md
      - Baixar Documento: tutorial/baixar-documento.md
