
name: Liberar nova versão

on:
  workflow_dispatch:
  push:
    tags:
      - '4.*'

jobs:

  package:
    runs-on: ubuntu-20.04
    name: Empacotar executavel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Ajustando Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Sao_Paulo"
          timezoneMacos: "America/Sao_Paulo"
          timezoneWindows: "America/Sao_Paulo"
      - name: Criando executavel
        run: |
          mvn versions:set -DnewVersion=${{github.ref_name}}
          mvn -B package -Passembly --file pom.xml

      - name: Criando pasta para Zip
        run: mkdir java-cte && cp target/java-cte-${{github.ref_name}}.jar java-cte && cp schemas.zip java-cte
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r java-cte-${{github.ref_name}}.zip java-cte

      - name: Criando release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Subir executavel (zip) para release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./java-cte-${{github.ref_name}}.zip
          asset_name: java-cte-${{github.ref_name}}.zip
          asset_content_type: application/zip
